version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Angular CLI"
      - npm install -g @angular/cli@17
  pre_build:
    commands:
      - echo "installing dependencies"
      - npm install
  build:
    commands:
      - echo "Building the application"
      - ng build -c production      # will place all build artifacts under a specific local folder (dist/my-angular-project) in the build environment
artifacts:
  files:
    - 'dist/my-angular-project/**/*'  # Which files should be included from dist/my-angular-project directory. Path varies based on application
    - appspec.yml
    - 'scripts/**/*'